### ISSUE TITLE
README link to LICENSE is broken

### ISSUE THREAD

**Issue by PixelPartner** [readyplayerme/animation-library#5]
The added LICENSE file does not really use Markdown syntax and the link points to LICENSE.md instead of LICENSE.
So I suggest to rename the file and to properly use markdown formatting inside.

**Comment by PixelPartner** [comment]
Sorry to intervene.
The link still doesn't work. Needs editing and testing README.md as well

**Comment by srcnalt** [comment]
No worries, thanks for spotting it. I thought there were only one links to license in the readme, but apparently there were 2 of them. Both fixed.
